### ISSUE TITLE
Item comparison when selecting from multiple items in /web broken

### ISSUE THREAD

**Issue by larsgw** [zotero/translation-server#105]
This line compares selected items to the items from the original session:

https://github.com/zotero/translation-server/blob/2dfd9dcb19ab45323a23eb88277a64c48e99ecd4/src/webSession.js#L349

The comparison above does not work if `this.items[i]` is an object, since the two can never be the exact same instances. Although Zotero [seems to specify](https://github.com/zotero/zotero/blob/d13ffcd9a3dec5edfcf86a0f10841d2e7e0ea380/chrome/content/zotero/xpcom/translation/translate.js#L1003-L1008) that items in the `select` handler should be strings, not objects, some translators (like [`PubMed.js`](https://github.com/zotero/translators/blame/f4612dea45f9f784203d53f87683be37283bc33d/PubMed.js#L172-L175)) do not follow that specification.

As for a fix, I can make a PR that compares the serialized JSON of both items instead, which should be sufficient since one of the two has been serialized already.

**Comment by dstillman** [comment]
I went with a slightly different fix, but thanks for catching this!
