### ISSUE TITLE
Support documents with content type "application/xhtml+xml"

### ISSUE THREAD

**Issue by shadeMe** [zotero/translation-server#108]
The translation server currently rejects valid remote documents that have Content-Type set to "application/xhtml+xml". 

Steps to reproduce:
* Request: ```curl -d 'https://www.hindawi.com/journals/jcrim/2014/' -H 'Content-Type: text/plain' http://127.0.0.1:1969/web```
* Response: ```The remote document is not in a supported format```

Translation server log: 
 ```
 (3)(+0676923): HTTP GET https://www.hindawi.com/journals/jcrim/2014/

 (1)(+0000388): Error: application/xhtml+xml; charset=utf-8 is not supported
 ```

**Comment by dstillman** [comment]
Fixed. Thanks for reporting!
