### ISSUE TITLE
How to use text search

### ISSUE THREAD

**Issue by jovrtn** [zotero/translation-server#137]
Not sure if there's a better support forum for this, but not sure how to get text search to work when building the Docker image. Any strings I `POST` to the /search endpoint all come back with `No identifier found`. I was expecting similar results to what the endpoint zbib.org uses: https://t0guvf0w17.execute-api.us-east-1.amazonaws.com/Prod/search (assuming it's running a version of this translation server).

Any help would be appreciated. Thanks!

**Comment by dstillman** [comment]
Sorry, text search isn't part of the public functionality — it requires various resources and processes we're not able to make available.

**Comment by jovrtn** [comment]
Is there any documentation available on the "various resources and processes" needed to make this work, assuming they were supplied/managed by someone implementing the translation server rather than a central provider?
