### ISSUE TITLE
Node.js 10 End of life

### ISSUE THREAD

**Issue by mtrojan-ub** [zotero/translation-server#139]
The Dockerfile still seems to be using Node.js 10.7, but version 10 seems to have reached end of life at Apr 2021. Current LTS versions are 14 (Apr 2023) or even 16 (Sep 2023). Are there any plans for upgrading?

https://endoflife.date/nodejs
https://github.com/zotero/translation-server/blob/master/Dockerfile

**Comment by dhimmel** [comment]
Noting that nodejs 14+ is actually required as per https://github.com/zotero/translation-server/issues/140, so the Dockerfile is definitely outdated.
