### ISSUE TITLE
Web query returning multiple results with  single=1 on some websites

### ISSUE THREAD

**Issue by SterlingHooten** [zotero/translation-server#145]
From my understanding sending a request with `/web?single=1` should return some generic metadata about the website. But when sending a request like this to `https://math.stackexchange.com/questions/450147/convolution-intuition-clarifying-terence-taos-blurring-fuzz-interpretation` I still receive items in the response:

```
{"url":"https://math.stackexchange.com/questions/450147/convolution-intuition-clarifying-terence-taos-blurring-fuzz-interpretation",
"session":"WHJQyvM2tUhUWgv","items":{"question":"Q: On this math.MO post, 
\"What is convolution intuitively?\", Terence Tao's answer
 (in the case where one function is a bump function) involves \"blurring\" and \"fuzz.\""
,"answer-450357":"A: Consider a function $f_1$: $$f_1(x)=\\delta(x)$$ 
where $\\delta(x)$ is Dirac delta, and a Gaussian function
 $g(x)$: $$g(x)=\\frac1{\\sigma\\sqrt{2\\pi}}\\exp\\left(-\\frac{x^2}{2\\sigma^2}\\right).$$
 One of main properties of Dirac delta is this: 
$$\\int_{-\\infty}^\\infty q(x)\\delta(x-x_0)dx=q(x_0).\\tag1$$
 Thus, convolution of $f_1$ and $g$ will equal $g$. Let's see how it looks 
($f_1$ is red, $f_1*g$ is blue):",
"answer-450934":"A: I'll just answer this comment, 
since the rest seems to have been addressed satisfactorily."}}
```

Is this the intended behavior? If so, is there some deterministic way to just get the generic information?

I'm trying to integrate this with an Emacs Org mode capture system into org-bibtex and need a fallback option. If Zotero isn't capable of this I'll just write my own generator in elisp.

Thanks!

**Comment by dstillman** [comment]
Works fine for me:

```
$  curl -d https://math.stackexchange.com/questions/450147/convolution-intuition-clarifying-terence-taos-blurring-fuzz-interpretation -H 'Content-Type: text/plain' '127.0.0.1:1969/web?single=1'
[{"key":"KE8MSIJD","version":0,"itemType":"webpage","creators":[],"tags":[],"websiteTitle":"Mathematics Stack Exchange","url":"https://math.stackexchange.com/questions/450147/convolution-intuition-clarifying-terence-taos-blurring-fuzz-interpretation","title":"analysis - Convolution intuition: clarifying Terence Tao's \"blurring\"/\"fuzz\" interpretation","language":"en","accessDate":"2022-12-07T06:05:42Z","shortTitle":"analysis - Convolution intuition"}]
```

**Comment by SterlingHooten** [comment]
> Works fine for me:
> 
> ```
> $  curl -d https://math.stackexchange.com/questions/450147/convolution-intuition-clarifying-terence-taos-blurring-fuzz-interpretation -H 'Content-Type: text/plain' '127.0.0.1:1969/web?single=1'
> [{"key":"KE8MSIJD","version":0,"itemType":"webpage","creators":[],"tags":[],"websiteTitle":"Mathematics Stack Exchange","url":"https://math.stackexchange.com/questions/450147/convolution-intuition-clarifying-terence-taos-blurring-fuzz-interpretation","title":"analysis - Convolution intuition: clarifying Terence Tao's \"blurring\"/\"fuzz\" interpretation","language":"en","accessDate":"2022-12-07T06:05:42Z","shortTitle":"analysis - Convolution intuition"}]
> ```

Thanks for testing it. I ran the same command it came back the same way as in my original post.

I was using the docker version, which appears to be 2 years old. Switching to the npm installed version seems to have fixed it. Thanks!
