### ISSUE TITLE
Implement /export

### ISSUE THREAD

**Issue by dstillman** [zotero/translation-server#5]

**Comment by dstillman** [comment]
'bibtex' and 'csljson' don't yet work. Others possibly broken as well.

`./translate_export bibtex` fails with `ZU.XRegExp is not a constructor`.

**Comment by zuphilip** [comment]
I see that CSV export is missing and some others too: Endnote, RefWorks, Evernote (maybe more). Can we add them to the list of supported formats as well?

**Comment by dstillman** [comment]
Added. (If anyone has better suggestions for the content types, let me know.)

**Comment by dstillman** [comment]
@mvolz: Now that /export is generally working, I suspect we'll be able to fix BibTeX export in the next few days, if you do want to keep that functionality for Citoid.

**Comment by mvolz** [comment]
That would be great, our timeline for deployment is 1-2 months anyway, and it turns out like 1/4 of our traffic is bibtex exports for some unknown reason :D.

**Comment by zuphilip** [comment]
> Added. (If anyone has better suggestions for the content types, let me know.)

Thank you very much!

**Comment by dstillman** [comment]
@mvolz: BibTeX should be good to go.
