### ISSUE TITLE
Failing test on master for search endpoint

### ISSUE THREAD

**Issue by mvolz** [zotero/translation-server#60]
As per comment here: https://gerrit.wikimedia.org/r/#/c/mediawiki/services/zotero/+/479020/
```
1) /search
       should perform a text search:

      AssertionError: expected 501 to equal 300
      + expected - actual

      -501
      +300
      
      at Context.<anonymous> (test/search_test.js:59:10)
      at process._tickCallback (internal/process/next_tick.js:68:7)
````
"The failing test is at https://github.com/zotero/translation-server/blob/master/test/search_test.js#L54. That should help narrow down what exactly is failing and how to fix it"

**Comment by dstillman** [comment]
Test fixed, thanks. (Text search is a non-public feature that requires an AWS Lambda call in our infrastructure.)
